Vagrant.configure("2") do |config|

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vsphere'

{{lab}}

{{extensions}}

# auto-load .env if vagrant-env installed
if Vagrant.has_plugin?("vagrant-env") then
  config.env.enable # Enable vagrant-env(.env)
end

{% if use_provisioning_vm %}
boxes.append(
    { :name => "PROVISIONING",
      :ip => "{{ip_range}}.3",
      :box => "bento/ubuntu-22.04",
      :box_version => "202401.31.0",
      :os => "linux",
      :cpus => 2,
      :mem => 2000,
      :forwarded_port => [ {:guest => 22, :host => 2210, :id => "ssh"} ]
    }
)
{% endif %}

  # disable rdp forwarded port inherited from StefanScherer box
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true, disabled: true

  # no autoupdate if vagrant-vbguest is installed
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600
  config.winrm.retry_limit = 30
  config.winrm.retry_delay = 10

  boxes.each do |box|
    config.vm.define box[:name] do |target|
      # BOX
      target.vm.provider :vsphere do |v|
        v.host = ENV['GOAD_VAGRANT_VCENTER_HOSTNAME']
        v.user = ENV['GOAD_VAGRANT_VCENTER_USERNAME']
        v.password = ENV['GOAD_VAGRANT_VCENTER_PASSWORD']
        v.datacenter_name = ENV['GOAD_VAGRANT_VCENTER_DATACENTER']
        v.compute_resource_name = ENV['GOAD_VAGRANT_VCENTER_CLUSTER']
        v.datastore_name = ENV['GOAD_VAGRANT_VCENTER_DATASTORE']
        v.networks = [ ENV['GOAD_VAGRANT_VCENTER_NET_NAT'], ENV['GOAD_VAGRANT_VCENTER_NET_DOMAIN'] ]
        v.insecure = (ENV['GOAD_VAGRANT_VCENTER_INSECURE'] == 'true')
        v.name = box[:name]
      end

      target.vm.box_download_insecure = box[:box]
      target.vm.box = box[:box]
      if box.has_key?(:box_version)
        target.vm.box_version = box[:box_version]
      end

      # issues/49
      target.vm.synced_folder '.', '/vagrant', disabled: true

      # IP
      target.vm.network :private_network, ip: box[:ip]

      # OS specific
      if box[:os] == "windows"
        target.vm.guest = :windows
        target.vm.communicator = "winrm"
        target.vm.provision :shell, :path => "../../../vagrant/Install-WMF3Hotfix.ps1", privileged: false
        target.vm.provision :shell, :path => "../../../vagrant/ConfigureRemotingForAnsible.ps1", privileged: false

        # fix ip for vmware
        if ENV['VAGRANT_DEFAULT_PROVIDER'] == "vsphere"
          target.vm.provision :shell, :path => "../../../vagrant/fix_ip.ps1", privileged: false, args: box[:ip]
        end
      else
        target.vm.communicator = "ssh"
      end

      if box.has_key?(:forwarded_port)
        # forwarded port explicit
        box[:forwarded_port] do |forwarded_port|
          target.vm.network :forwarded_port, guest: forwarded_port[:guest], host: forwarded_port[:host], host_ip: "127.0.0.1", id: forwarded_port[:id]
        end
      end

    end
  end
end
